name: build installers

on:
  workflow_dispatch:

jobs:

  build-windows-installer:
    name: Build Installer on Windows
    runs-on: windows-latest
    steps:

# SETUP BUILD ENVIRONMENT
    - id: checkout-code
      name: Checkout code
      uses: actions/checkout@v3
    - id: setup-jdk
      name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17

    - id: package
      name: Maven Package
      run: |
        mvn package

    - id: jpackage
      name: jpackage
      run: >
        jpackage 
          --input target/ 
          --name sterling 
          --main-jar sterling-1.0-SNAPSHOT.jar 
          --main-class com.sterling.automation.App 
          --type exe 
          --dest ./dist

    - id: upload-installer
      name: Upload installer
      uses: actions/upload-artifact@v4
      with:
        path: ./dist/sterling.exe
        name: windows-installer
        retention-days: 1
